-- Create tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  title TEXT NOT NULL,
  description TEXT,
  due_date TIMESTAMP,
  completed BOOLEAN NOT NULL DEFAULT false,
  completed_at TIMESTAMP,
  goal_id INTEGER REFERENCES goals(id),
  priority TEXT NOT NULL DEFAULT 'medium',
  color_scheme INTEGER NOT NULL DEFAULT 1,
  deleted_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add completion_history column to habits table
ALTER TABLE habits ADD COLUMN IF NOT EXISTS completion_history JSONB DEFAULT '{}';
ALTER TABLE habits ADD COLUMN IF NOT EXISTS color_scheme INTEGER NOT NULL DEFAULT 1;

-- Update goals table
ALTER TABLE goals ADD COLUMN IF NOT EXISTS start_date TIMESTAMP;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'in_progress';
ALTER TABLE goals ADD COLUMN IF NOT EXISTS depends_on JSONB DEFAULT '[]';
ALTER TABLE goals ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE goals ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;